//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADE_ManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public long Id { get; set; }
        public string CurrentColumnName { get; set; }
        public string NextColumnName { get; set; }
        public bool IsDeleted { get; set; }
        public string DeleterUserId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public string LastModifierUserId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public string CreatorUserId { get; set; }
        public string Title { get; set; }
    }
}
